### ISSUE TITLE
consider splitting the lib into two

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/bind-it#1]
one module `bind-last` and one `bind-first`. as @jussi-kalliokoski [suggested](https://twitter.com/quinnirill/status/628279773597405184).

What do you think at @tomekwi? I actually think it's okay to keep this two together (they are so small and similar and probably want change ever).

**Comment by stoeffel** [comment]
I did it anyways. Will delete this repo soon.

https://github.com/stoeffel/bind-first
https://github.com/stoeffel/bind-last

//cc @tomekwi  @jussi-kalliokoski

**Comment by tomek-he-him** [comment]
:+1:
